//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvcControlerAcesso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public int COD_USUARIO { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string EMAIL { get; set; }
        public string SENHA { get; set; }
        public Nullable<int> COD_CARGO { get; set; }
    
        public virtual TB_CARGO TB_CARGO { get; set; }
    }
}
